/**
 * OSRS quest database.
 *
 * Quest IDs are wiki page names (e.g. "Animal Magnetism", "Dragon Slayer II").
 * Data is generated by scripts/fetch-quest-reqs.ts — re-run to update.
 */

import questDataJson from './quest-data.json';

export interface SkillReq {
  skill: string;
  level: number;
  boostable: boolean;
}

export interface QuestEntry {
  name: string;
  difficulty: 'novice' | 'intermediate' | 'experienced' | 'master' | 'grandmaster';
  members: boolean;
  skillReqs: SkillReq[];
  questReqs: string[]; // wiki quest names
  questPoints: number;
}

export const QUEST_DATABASE = questDataJson as Record<string, QuestEntry>;

export function getQuestName(questId: string): string {
  return QUEST_DATABASE[questId]?.name ?? questId;
}

export const ALL_QUESTS = Object.values(QUEST_DATABASE).sort((a, b) =>
  a.name.localeCompare(b.name),
);
